# Generated by Django 5.0.14 on 2025-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiantes", "0002_alter_estudiante_cursos_inscripcion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="cursos",
            field=models.ManyToManyField(
                blank=True, related_name="estudiantes", to="estudiantes.curso"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("estudiante", "curso"), name="unique_inscripcion"
            ),
        ),
    ]
